name: deploy UI to remote server
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "docker-compose.yml"
          target: "sawyerburnett-nextjs"
          rm: true
      - name: run bash script
        uses: appleboy/ssh-action@master
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: CR_PAT
          script: |
            cd sawyerburnett-nextjs/

            # build a new docker container based upon updated repository
            docker login https://ghcr.io/burnett2k -u burnett2k -p $CR_PAT
            docker pull ghcr.io/burnett2k/sawyerburnett-nextjs:latest

            # start the docker container
            docker-compose up -d

            echo "cleaning up dingleberries"
            docker system prune -a -f

            # list currently running containers
            docker ps
